### ISSUE TITLE
방송영상 썸네일에 들어갈 이미지를 선택해주세요~

### ISSUE THREAD

**Issue by pineoc** [studiopluto/home#15]
![thumbnail-test1](https://user-images.githubusercontent.com/5077086/34375341-64b16ec8-eb29-11e7-9dd0-83a9dd194710.jpg)
![thumbnail-test2](https://user-images.githubusercontent.com/5077086/34375342-64db13ae-eb29-11e7-9296-ee7a992bb77c.jpg)

위의 이미지를 썸네일로 사용하고 각 참여자별로 @ 을 붙여서 밑에 리스트하려고 합니다.
썸네일 이미지에 추가적으로 수정할 사항이 있다면 말씀해주세요~

**Comment by miconblog** [comment]
능력자! 전 1번!

**Comment by pineoc** [comment]
![thumbnail-fix](https://user-images.githubusercontent.com/5077086/34376436-0bc9cec6-eb2f-11e7-86cc-07572b31e94b.jpg)

최종 이미지입니다.

**Comment by pineoc** [comment]
출연자가 오른쪽 밑에 있어서 영상 플레이 타임과 겹칩니다.
중간으로 옮겨서 수정했습니다.

![thumbnail-fix2](https://user-images.githubusercontent.com/5077086/34377578-02cba302-eb35-11e7-91a2-ae3b3a18493e.jpg)

**Comment by pineoc** [comment]
1번 작업한대로 첫 방송에 대한 썸네일 입력되었습니다.
추가적으로 모바일 대응을 하긴 해야겠네요.
동영상을 봤을때 밑에 빨간 프로그래스바가 생기는데 출연자 텍스트 밑에 마진을 좀 줘야겠습니다. ㅎㅎ

**Comment by miconblog** [comment]
수고하셨습니다! 짱짱맨~~ 든든 합니다!!

**Comment by pineoc** [comment]
이미지 업로드했으니 이 이슈는 닫겠습니다.

**Comment by asbubam** [comment]
수고하셨습니다!
