### ISSUE TITLE
유튜브 채널 아트를 골라주세요!

### ISSUE THREAD

**Issue by pineoc** [studiopluto/home#16]
![channel-art](https://user-images.githubusercontent.com/5077086/34378197-154ab786-eb38-11e7-8d15-8685d1c52503.jpg)
![channel-art2](https://user-images.githubusercontent.com/5077086/34378198-1574dae8-eb38-11e7-9141-a54abd3b71e5.jpg)
![channel-art3](https://user-images.githubusercontent.com/5077086/34378199-159e3e4c-eb38-11e7-8406-a29cfa22c8dd.jpg)

중간에 이미지, 텍스트를 넣는 이유는,

![image](https://user-images.githubusercontent.com/5077086/34378245-3ab7f29a-eb38-11e7-9829-5f67b4f59671.png)
(출처: http://jennysharehouse.tistory.com/48)

이렇게 작업해야 모바일, 컴퓨터, TV에 대응할 수 있기 때문입니다.

저는 일단 2번은 사실 뻘짓한번 해봤고 다른거 1번 아니면 3번으로..

**Comment by J2P** [comment]
전 2번이 좋긴한데요...

그 동그라미 퍼져 나가는게 정확하게 행성이랑 맞으면 좋을거 같아요~

**Comment by SsureyMoon** [comment]
저는 2, 1, 3 순으로 좋습니다.

**Comment by miconblog** [comment]
와~ 2번 빨려들어가네요~ ㅋㅋㅋ 저도 2번!

**Comment by ecleya** [comment]
저는 1, 2, 3순이요.

**Comment by pineoc** [comment]
동그랗게 퍼져나가는건 저 송신탑에서 부터 나오라고 했던거긴 합니다. ㅎㅎㅎ 2번이 의외로 반응이 좋군요?!

**Comment by pineoc** [comment]
쌍피님 말씀대로 한번 중간에서 퍼져나가는 걸로 작업해보았습니다.

![channel-art4](https://user-images.githubusercontent.com/5077086/34398716-623feaca-ebc4-11e7-8259-cb2763c69b57.png)

의견주세요~

**Comment by J2P** [comment]
오오오 저는 이게 좋네요 ㅋㅋㅋ

**Comment by rotoshine** [comment]
저도 2번에 가운데 맞춘 게 좋네요~

**Comment by pineoc** [comment]
채널아트 2번에 가운데로 맞춘 이미지로 올려두었습니다~
이슈 닫겠습니다.
