### ISSUE TITLE
플루토 홈페이지에 있는 로고를 바꿔야합니다.

### ISSUE THREAD

**Issue by pineoc** [studiopluto/home#17]
문님이 만들어주신 로고로 바꾸는게 어떨까요?

<img width="271" alt="logo" src="https://user-images.githubusercontent.com/5077086/34400376-ef32a3a0-ebd3-11e7-88a5-acf0781be136.png">

**Comment by pineoc** [comment]
#4 이슈와 연관되어 있습니다.

**Comment by SsureyMoon** [comment]
바꾸어도 좋을 것 같습니다

**Comment by pineoc** [comment]
사실 지금 있는 로고파일이 어디에 저장되어있는지 모르겠습니다 ㅠㅠ

**Comment by SsureyMoon** [comment]
https://github.com/studiopluto/home/tree/master/themes/icarus/source/css/images 에 있습니다. ㅎ

**Comment by pineoc** [comment]
오오오오 감사합니다 문님 ㅎㅎㅎ

**Comment by pineoc** [comment]
PR은 했지만 추가적으로 플루토 org 이미지도 수정해야하네요.
이슈에 있는 이미지로 수정 부탁드립니다. @miconblog
