### ISSUE TITLE
두번째 시험방송 날짜를 잡아봐요!!

### ISSUE THREAD

**Issue by miconblog** [studiopluto/home#19]
### 두번째 방송 주제는 "리모트 워크" 입니다. 

최근에 @outsideris 님도 바지벗고 일해도 되나요? 라는 책을 보고 리뷰를 남겨주셨고, 
저도 나름 관련해서 많은 생각들을 해오고 있어서 같이 얘기해보면 좋을것 같습니다. 

### 언제 할까요?
슬랙 채널에서 얘기나온 날짜는 현재 이렇습니다. 
 
 - 2018년 1월 2일(화) 
 - 2018년 1월 4일(목)
 - 2018년 1월 5일(금) 

가능한 모든 시간대와 날짜를 댓글로 남겨주세요. 

### 이번엔 모여서 한번 해볼까요?
장소를 아직 정하진 않았지만 테스트하는 김에 모여서 해보면 어떨까 싶어서 
모여서 해보는것도 괜찮지 않을까 싶습니다. 
장소는 일단 날짜를 먼저 정하고 조용한 곳으로 물색을 해보죠~

**Comment by rotoshine** [comment]
저는 2일, 5잉이 좋습니다!

**Comment by pineoc** [comment]
저는 4일, 5일!

**Comment by outsideris** [comment]
저는 2,4,5 다 괜찮습니다.(하...한가해 ㅠ)

**Comment by asbubam** [comment]
저는 4,5 일 좋습니다. :)

**Comment by miconblog** [comment]
모두가 만족하는 5일 어떨까요?

**Comment by ecleya** [comment]
언제든 괜찮습니다. 그러니... 5일? ㅎㅎ

**Comment by pineoc** [comment]
장소는 위워크나..? 코워킹 스페이스는 조용한 공간이 있으려나요?

**Comment by rotoshine** [comment]
5일로 결정이군요!

5일에 팀점(?)하고 졸린 두시쯤부터 달리는건가요!

**Comment by pineoc** [comment]
팀점 좋습니다!
점심먹고 다같이 노곤노곤..ㅋㅋㅋㅋㅋ

**Comment by miconblog** [comment]
그럼 일단 다음 방송은 5일로 fix 합니다.
