### ISSUE TITLE
플루토 파비콘 개선하기

### ISSUE THREAD

**Issue by miconblog** [studiopluto/home#22]
풀루토 로고를 그대로 파비콘으로 쓰니까 너무 작아서 잘 안보이기도 하고, 일단 파비콘 배경이 흰색인데 안테나나 번개 모양등이 잘 안보입니다. 

파비콘은 반원위에 안테나만 세운 별도 아이콘으로 가도 되지 않을까 싶네요.

**Comment by SsureyMoon** [comment]
<img width="26" alt="favicon1" src="https://user-images.githubusercontent.com/7412334/34508379-f8b01662-f081-11e7-91e6-d29b71baca35.png">
<img width="26" alt="favicon2" src="https://user-images.githubusercontent.com/7412334/34508380-f8e4d974-f081-11e7-988c-efbec9369c87.png">
위 두개는 어떤가요??

**Comment by rotoshine** [comment]
위에꺼 괜찮아보입니다! 번개나 레이더 효과 같은 거 넣으면 안 보이려나요?

**Comment by SsureyMoon** [comment]
<img width="26" alt="favicon3" src="https://user-images.githubusercontent.com/7412334/34606642-81aeea42-f253-11e7-98e9-1fa9a1d62637.png">
번개는 잘 안보여서, 레이더 효과를 넣었습니다.

**Comment by miconblog** [comment]
검정색이 잘 안보여서 노란색으로 안테나랑 레이더를 그리면 어떤 느낌일까요?

**Comment by SsureyMoon** [comment]
<img width="26" alt="favicon4" src="https://user-images.githubusercontent.com/7412334/34611732-061b486e-f26a-11e7-971d-60e774653d74.png">
<img width="26" alt="favicon5" src="https://user-images.githubusercontent.com/7412334/34611737-08eb5a98-f26a-11e7-8d63-4281705176b6.png">
이런 느낌입니다. 파란 바탕이라 노란색이 잘 안보이는 것 같습니다.

**Comment by SsureyMoon** [comment]
![favicon6_52x52](https://user-images.githubusercontent.com/7412334/34646566-09ca8588-f3af-11e7-930b-68dc80fc8e19.png)
처음에 나왔던 반원 위의 안테나가 더 깔끔한 것 같습니다.

**Comment by pineoc** [comment]
그러게요 검은색으로 만든게 좋네용. ㅎㅎ

**Comment by miconblog** [comment]
색상을 반전해서 깃헙 처럼 검은 바탕에 흰색은 어때요?

**Comment by SsureyMoon** [comment]
![favicon7](https://user-images.githubusercontent.com/7412334/34646765-5117ee58-f3b4-11e7-9569-582a48a6c1ef.png)
![tabtab](https://user-images.githubusercontent.com/7412334/34646774-8781ccca-f3b4-11e7-9967-2125ac0a1a90.png)

이런 느낌 입니다 ㅋㅋ

**Comment by pineoc** [comment]
오오오... 👍

**Comment by asbubam** [comment]
엄청 이뻐요!

**Comment by miconblog** [comment]
오 좋다!! PR 주세요!!

**Comment by J2P** [comment]
대박 디자이너문~
