### ISSUE TITLE
방송 요청하기

### ISSUE THREAD

**Issue by byeonggukgong** [studiopluto/home#28]
# 방송 요청하기

### 주제
1. (고민상담) 개발에 정석은 존재할까요?
2. (고민상담) 어설픈 완벽주의 때문에 진척도가 보이질 않습니다!

### 설명
1. 토이 프로젝트로 파이썬 API 래퍼를 개발하고 있습니다. 성격 상 정석을 추구하는 편인데, 여러
 우수한 개발자분들의 프로젝트를 참고하면서 각자의 개성(?)에 따라 개발되어 정석이라고 말할 것이 없다는 생각을 크게 하게됬습니다. 그래도 현업에서 종사하신 분들이 파이썬 API 래퍼를 개발할 때 이것만큼은 지켰으면 하는 것이나 자신과의 약속처럼 지키고있는 부분이 있다면 알고싶습니다.

2. 평소에 깃허브 탐험(?)을 통해서 질 좋은 타 개발자의 코드를 읽습니다. 이렇게 질 좋은 코드에 익숙해진 나머지 제가 개발한 코드를 보면 암담하며 작게는 함수 하나를 통째로 날리고 새로 개발하고 크게는 프로젝트 구조 자체를 뒤집어 엎는 경우까지 있습니다. 이런 반복이 과연 지금은 고통스럽고 힘들지만 미래에 도움이 될지 의문입니다. 이런 상황에 대한 진솔한 조언 또는 일침 듣고싶습니다.

## 방송시간
방송 시간은 크게 중요하지 않다고 봅니다. 오히려 방송 중 나오는 이야기를 10~15분 가량으로 짧게 끊어서 스낵 비디오처럼 볼 수 있다면 구독자 입장에서 부담가지지 않고 원하는 이야기를 듣기 좋을 것 같습니다.

**Comment by miconblog** [comment]
첫 이슈 등록 감사합니다~ :) 다음 방송에 깊이 있는 고민 같이 해보겠습니다.

**Comment by J2P** [comment]
첫 방송 요청 감사합니다~ 알찬 내용으로 찾아뵙겠습니다~

**Comment by outsideris** [comment]
첫 요청해 주신 부분은 https://studiopluto.github.io/home/2018/01/18/2018-01-30/ 에서 내일 다룰 예정입니다.

**Comment by outsideris** [comment]
방송했으므로 닫습니다.
