### ISSUE TITLE
고민 상담 후기

### ISSUE THREAD

**Issue by byeonggukgong** [studiopluto/home#33]
# 감사합니다 :)

홀로 하던 고민들을 현업 개발자님들의 다양한 시각에서 진솔하게 상담을 해주셔서 상당히 도움이 되었어요. 또, 고민 상담 간간히 **담백한 칭찬**과 **알찬 피드백**을 해주셔서 좀 더 확신과 자신을 가지고 개발에 정진할 수 있을 것 같아요.

다시 한번 감사합니다!

# 이런 점은 개선하면 좋을 것 같아요

* 출연자분들께서 **닉네임 뱃지**를 달고 방송하시면 시청자 입장에서 화자가 바뀔 때 찾기 위해 시선을 방황하는 시간을 획기적으로 줄일 수 있을 것 같아요.
* 유튜브 **책갈피(?) 또는 설명란에 방송 스케쥴을 작성**해두면 시청자가 좀 더 듣고자 하는 내용을 찾는데 편리할 것 같아요.
* 중간중간 끊겨서(아마 송수신 상태가 파도를 타버려서겠죠?) 주옥같은 멘트들을 놓치는 경우가 생겨서 아쉬웠어요. 가능하다면 자막을 달면 좀 더 보는데 편하지않을까 생각해요.

**Comment by miconblog** [comment]
고민 상담도 해주시고 방송 피드백까지~!! 감사합니다. :) 도움이 되셨다니 더 열심히 해야겠네요~

제안주신 내용들은 슬랙에서 좀더 논의 해보겠습니다!

**Comment by outsideris** [comment]
아이디어 감사합니다. 닉네임 뱃지랑 화자를 알려주는 건 참 좋을 것 같네요.  저희도 방송을 하면서 하나씩 배워가고 있네요.
